# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "elastic-mapreduce"
  s.version = "2015.02.23"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Amazon.com", "Koichi Fujikawa"]
  s.date = "2012-06-28"
  s.description = "Original is official but this is Unofficial gem."
  s.email = "fujibee@hapyrus.com"
  s.executables = ["elastic-mapreduce"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README",
    "README.header"
  ]
  s.files = [
    ".gitmodules",
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "NOTICE.txt",
    "README",
    "README.header",
    "Rakefile",
    "VERSION",
    "bin/elastic-mapreduce",
    "elastic-mapreduce.gemspec",
    "lib/amazon/aws/exceptions.rb",
    "lib/amazon/coral/awsquery.rb",
    "lib/amazon/coral/awsquerychainhelper.rb",
    "lib/amazon/coral/awsqueryhandler.rb",
    "lib/amazon/coral/awsqueryurihandler.rb",
    "lib/amazon/coral/call.rb",
    "lib/amazon/coral/dispatcher.rb",
    "lib/amazon/coral/ec2client.rb",
    "lib/amazon/coral/elasticmapreduceclient.rb",
    "lib/amazon/coral/handler.rb",
    "lib/amazon/coral/httpdelegationhelper.rb",
    "lib/amazon/coral/httpdestinationhandler.rb",
    "lib/amazon/coral/httphandler.rb",
    "lib/amazon/coral/identityhandler.rb",
    "lib/amazon/coral/job.rb",
    "lib/amazon/coral/logfactory.rb",
    "lib/amazon/coral/option.rb",
    "lib/amazon/coral/orchestrator.rb",
    "lib/amazon/coral/querystringmap.rb",
    "lib/amazon/coral/service.rb",
    "lib/amazon/coral/simplelog.rb",
    "lib/amazon/coral/urlencoding.rb",
    "lib/amazon/coral/v0signaturehandler.rb",
    "lib/amazon/coral/v0signaturehelper.rb",
    "lib/amazon/coral/v1signaturehandler.rb",
    "lib/amazon/coral/v1signaturehelper.rb",
    "lib/amazon/coral/v2signaturehandler.rb",
    "lib/amazon/coral/v2signaturehelper.rb",
    "lib/amazon/retry_delegator.rb",
    "lib/amazon/stderr_logger.rb",
    "lib/cacert.pem",
    "lib/client.rb",
    "lib/commands.rb",
    "lib/credentials.rb",
    "lib/ec2_client_wrapper.rb",
    "lib/elastic-mapreduce-cli.rb",
    "lib/elastic-mapreduce-json.rb",
    "lib/elastic-mapreduce-json/lexer.rb",
    "lib/elastic-mapreduce-json/objects.rb",
    "lib/run_tests.rb",
    "lib/simple_executor.rb",
    "lib/simple_logger.rb",
    "lib/uuidtools.rb",
    "lib/uuidtools/version.rb",
    "run_tests.rb",
    "samples/freebase/code/freebase_jobflow.json",
    "samples/similarity/lastfm_jobflow.json",
    "samples/wordSplitter.py",
    "tests/commands_test.rb",
    "tests/credentials.json",
    "tests/example.json"
  ]
  s.homepage = "http://github.com/hapyrus/elastic-mapreduce"
  s.licenses = ["Apache License"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Amazon's commandline client for EMR (Elastic Map-Reduce) invocation (Unofficial Gem and Ruby 1.9 Version)"

end

